[package]
name = "vanity-solana"
version = "0.1.0"
edition = "2021"

[dependencies]
ed25519-dalek = { version = "2", features = ["rand_core"] }
rand = "0.8"
rand_chacha = "0.3"
bs58 = "0.5"
num_cpus = "1"
core_affinity = "0.8"


[profile.release]
lto = true
codegen-units = 1
opt-level = 3
